seqkit sort --quiet -n -i ../e_remove_duplicates_output/KF156836.cln.fa &> ../e_remove_duplicates_sorted_output/KF156836.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/KF156836.cln.fa &> ../e_remove_duplicates_sorted_output/KF156836.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/KF156836.cln.fa &> ../e_remove_duplicates_sorted_output/KF156836.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/KU878156.cln.fa &> ../e_remove_duplicates_sorted_output/KU878156.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/KU878156.cln.fa &> ../e_remove_duplicates_sorted_output/KU878156.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/KU878156.cln.fa &> ../e_remove_duplicates_sorted_output/KU878156.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/KX904873.cln.fa &> ../e_remove_duplicates_sorted_output/KX904873.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/KX904873.cln.fa &> ../e_remove_duplicates_sorted_output/KX904873.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/KX904873.cln.fa &> ../e_remove_duplicates_sorted_output/KX904873.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359935.cln.fa &> ../e_remove_duplicates_sorted_output/MF359935.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359935.cln.fa &> ../e_remove_duplicates_sorted_output/MF359935.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359935.cln.fa &> ../e_remove_duplicates_sorted_output/MF359935.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359937.cln.fa &> ../e_remove_duplicates_sorted_output/MF359937.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359937.cln.fa &> ../e_remove_duplicates_sorted_output/MF359937.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359937.cln.fa &> ../e_remove_duplicates_sorted_output/MF359937.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359943.cln.fa &> ../e_remove_duplicates_sorted_output/MF359943.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359943.cln.fa &> ../e_remove_duplicates_sorted_output/MF359943.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359943.cln.fa &> ../e_remove_duplicates_sorted_output/MF359943.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359952.cln.fa &> ../e_remove_duplicates_sorted_output/MF359952.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359952.cln.fa &> ../e_remove_duplicates_sorted_output/MF359952.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MF359952.cln.fa &> ../e_remove_duplicates_sorted_output/MF359952.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MN078090.cln.fa &> ../e_remove_duplicates_sorted_output/MN078090.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MN078090.cln.fa &> ../e_remove_duplicates_sorted_output/MN078090.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MN078090.cln.fa &> ../e_remove_duplicates_sorted_output/MN078090.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MN711645.cln.fa &> ../e_remove_duplicates_sorted_output/MN711645.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MN711645.cln.fa &> ../e_remove_duplicates_sorted_output/MN711645.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MN711645.cln.fa &> ../e_remove_duplicates_sorted_output/MN711645.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MZ073672.cln.fa &> ../e_remove_duplicates_sorted_output/MZ073672.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MZ073672.cln.fa &> ../e_remove_duplicates_sorted_output/MZ073672.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/MZ073672.cln.fa &> ../e_remove_duplicates_sorted_output/MZ073672.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_007898.cln.fa &> ../e_remove_duplicates_sorted_output/NC_007898.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_007898.cln.fa &> ../e_remove_duplicates_sorted_output/NC_007898.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_007898.cln.fa &> ../e_remove_duplicates_sorted_output/NC_007898.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_014697.cln.fa &> ../e_remove_duplicates_sorted_output/NC_014697.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_014697.cln.fa &> ../e_remove_duplicates_sorted_output/NC_014697.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_014697.cln.fa &> ../e_remove_duplicates_sorted_output/NC_014697.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_019616.cln.fa &> ../e_remove_duplicates_sorted_output/NC_019616.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_019616.cln.fa &> ../e_remove_duplicates_sorted_output/NC_019616.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_019616.cln.fa &> ../e_remove_duplicates_sorted_output/NC_019616.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_024663.cln.fa &> ../e_remove_duplicates_sorted_output/NC_024663.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_024663.cln.fa &> ../e_remove_duplicates_sorted_output/NC_024663.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_024663.cln.fa &> ../e_remove_duplicates_sorted_output/NC_024663.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_026690.cln.fa &> ../e_remove_duplicates_sorted_output/NC_026690.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_026690.cln.fa &> ../e_remove_duplicates_sorted_output/NC_026690.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_026690.cln.fa &> ../e_remove_duplicates_sorted_output/NC_026690.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_026691.cln.fa &> ../e_remove_duplicates_sorted_output/NC_026691.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_026691.cln.fa &> ../e_remove_duplicates_sorted_output/NC_026691.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_026691.cln.fa &> ../e_remove_duplicates_sorted_output/NC_026691.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_030786.cln.fa &> ../e_remove_duplicates_sorted_output/NC_030786.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_030786.cln.fa &> ../e_remove_duplicates_sorted_output/NC_030786.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_030786.cln.fa &> ../e_remove_duplicates_sorted_output/NC_030786.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_030789.cln.fa &> ../e_remove_duplicates_sorted_output/NC_030789.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_030789.cln.fa &> ../e_remove_duplicates_sorted_output/NC_030789.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_030789.cln.fa &> ../e_remove_duplicates_sorted_output/NC_030789.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_031376.cln.fa &> ../e_remove_duplicates_sorted_output/NC_031376.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_031376.cln.fa &> ../e_remove_duplicates_sorted_output/NC_031376.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_031376.cln.fa &> ../e_remove_duplicates_sorted_output/NC_031376.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_031428.cln.fa &> ../e_remove_duplicates_sorted_output/NC_031428.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_031428.cln.fa &> ../e_remove_duplicates_sorted_output/NC_031428.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_031428.cln.fa &> ../e_remove_duplicates_sorted_output/NC_031428.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_034914.cln.fa &> ../e_remove_duplicates_sorted_output/NC_034914.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_034914.cln.fa &> ../e_remove_duplicates_sorted_output/NC_034914.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_034914.cln.fa &> ../e_remove_duplicates_sorted_output/NC_034914.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_035705.cln.fa &> ../e_remove_duplicates_sorted_output/NC_035705.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_035705.cln.fa &> ../e_remove_duplicates_sorted_output/NC_035705.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_035705.cln.fa &> ../e_remove_duplicates_sorted_output/NC_035705.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_035709.cln.fa &> ../e_remove_duplicates_sorted_output/NC_035709.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_035709.cln.fa &> ../e_remove_duplicates_sorted_output/NC_035709.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_035709.cln.fa &> ../e_remove_duplicates_sorted_output/NC_035709.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_036052.cln.fa &> ../e_remove_duplicates_sorted_output/NC_036052.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_036052.cln.fa &> ../e_remove_duplicates_sorted_output/NC_036052.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_036052.cln.fa &> ../e_remove_duplicates_sorted_output/NC_036052.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_036306.cln.fa &> ../e_remove_duplicates_sorted_output/NC_036306.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_036306.cln.fa &> ../e_remove_duplicates_sorted_output/NC_036306.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_036306.cln.fa &> ../e_remove_duplicates_sorted_output/NC_036306.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_037472.cln.fa &> ../e_remove_duplicates_sorted_output/NC_037472.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_037472.cln.fa &> ../e_remove_duplicates_sorted_output/NC_037472.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_037472.cln.fa &> ../e_remove_duplicates_sorted_output/NC_037472.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_039973.cln.fa &> ../e_remove_duplicates_sorted_output/NC_039973.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_039973.cln.fa &> ../e_remove_duplicates_sorted_output/NC_039973.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_039973.cln.fa &> ../e_remove_duplicates_sorted_output/NC_039973.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_041473.cln.fa &> ../e_remove_duplicates_sorted_output/NC_041473.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_041473.cln.fa &> ../e_remove_duplicates_sorted_output/NC_041473.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_041473.cln.fa &> ../e_remove_duplicates_sorted_output/NC_041473.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_041602.cln.fa &> ../e_remove_duplicates_sorted_output/NC_041602.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_041602.cln.fa &> ../e_remove_duplicates_sorted_output/NC_041602.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_041602.cln.fa &> ../e_remove_duplicates_sorted_output/NC_041602.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_048520.cln.fa &> ../e_remove_duplicates_sorted_output/NC_048520.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_048520.cln.fa &> ../e_remove_duplicates_sorted_output/NC_048520.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_048520.cln.fa &> ../e_remove_duplicates_sorted_output/NC_048520.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_053764.cln.fa &> ../e_remove_duplicates_sorted_output/NC_053764.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_053764.cln.fa &> ../e_remove_duplicates_sorted_output/NC_053764.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_053764.cln.fa &> ../e_remove_duplicates_sorted_output/NC_053764.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_059012.cln.fa &> ../e_remove_duplicates_sorted_output/NC_059012.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_059012.cln.fa &> ../e_remove_duplicates_sorted_output/NC_059012.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_059012.cln.fa &> ../e_remove_duplicates_sorted_output/NC_059012.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_059942.cln.fa &> ../e_remove_duplicates_sorted_output/NC_059942.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_059942.cln.fa &> ../e_remove_duplicates_sorted_output/NC_059942.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/NC_059942.cln.fa &> ../e_remove_duplicates_sorted_output/NC_059942.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/OL450428.cln.fa &> ../e_remove_duplicates_sorted_output/OL450428.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/OL450428.cln.fa &> ../e_remove_duplicates_sorted_output/OL450428.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/OL450428.cln.fa &> ../e_remove_duplicates_sorted_output/OL450428.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/JQ757046.cln.fa &> ../e_remove_duplicates_sorted_output/JQ757046.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/JQ757046.cln.fa &> ../e_remove_duplicates_sorted_output/JQ757046.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/JQ757046.cln.fa &> ../e_remove_duplicates_sorted_output/JQ757046.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/JQ757046.cln.fa &> ../e_remove_duplicates_sorted_output/JQ757046.cln.sorted.fa
seqkit sort --quiet -n -i ../e_remove_duplicates_output/JQ757046.cln.fa &> ../e_remove_duplicates_sorted_output/JQ757046.cln.sorted.fa
